module ZenRuby
	module Config
		ZENDESK_API_URL = <YOUR_ZENDESK_API_URL>
		ZENDESK_USERNAME = <YOUR_ZENDESK_ADMIN_USERNAME>
		ZENDESK_TOKEN = <YOUR_ZENDESK_TOKEN/PASSWORD>

		TICKET_FIELD_ID = <YOUR_TICKET_FIELD_ID>

		GIT_LABEL = "YOUR LABEL TO TRACK"
		GIT_ISSUES_URL = 'GIT ISSUES API URL FOR YOUR TARGET REPO'
	end
end