module ZenRuby
	module Config
		ZENDESK_API_URL = <YOUR_ZENDESK_API_URL>
		ZENDESK_USERNAME = <YOUR_ZENDESK_ADMIN_USERNAME>
		ZENDESK_TOKEN = <YOUR_ZENDESK_TOKEN/PASSWORD>

		TICKET_FIELD_ID = <YOUR_TICKET_FIELD_ID>

		GIT_LABEL = <LABEL_TO_TRACK>
		GIT_ISSUES_URL = <GIT_ISSUE_API_URL>
		GIT_EMAIL = <YOUR_GIT_USER_EMAIL>
		GIT_OAUTH_TOKEN = <GIT_TOKEN>
	end
end
